[theme]
primaryColor="#000000"
backgroundColor="#ebebff"
secondaryBackgroundColor="#ffffff"
textColor="#020101"
page_title="Water Level Reporter"  # à¸à¸³à¸«à¸™à¸”à¸Šà¸·à¹ˆà¸­à¸‚à¸­à¸‡à¸«à¸™à¹‰à¸²à¹à¸­à¸›
page_icon="ğŸŒ«ï¸"  # à¸à¸³à¸«à¸™à¸”à¹„à¸­à¸„à¸­à¸™à¸‚à¸­à¸‡à¸«à¸™à¹‰à¸²à¹à¸­à¸›
layout="wide"  # à¸à¸³à¸«à¸™à¸”à¹€à¸¥à¸¢à¹Œà¹€à¸­à¸²à¸—à¹Œ
initial_sidebar_state="collapsed"  # à¸à¸³à¸«à¸™à¸”à¸ªà¸–à¸²à¸™à¸°à¹€à¸£à¸´à¹ˆà¸¡à¸•à¹‰à¸™à¸‚à¸­à¸‡ sidebar
[server]
font="sans serif"
# if you don't want to start the default browser:
headless = true
# you will need this for local development:
runOnSave = true
# you will need this if running docker on windows host:
fileWatcherType = "poll"